print ("my name is mary")
print ("i'm 14 years old")
print ("I'm from Georgia")
print (" i was born and raised here")
print (" i live in a family of 6")
print ("i have 2 younger brothers")
print ("one of them is 10 years old")
print ("and the other one is turning 3")
print ("i go to school, i'm in a 8th grade")
print ("i don't really have a free time")
print ("but when i had one, i used to spend it on useless games")
print (" until i joined GOA")
print ("after i joined GOA, everything took a turn")
print ("my life got better")
print ("GOA teached me that i can spend my free time on better things")
print ("such as programming")
print ("knowing programming is so helpful in life")
print ("it gets you a job, lot's of friends and future")
print ("it also teaches you how to become the best version of yourself")
print ("GOA has a frienldy environment and teaches you a lot's of good things about programming")
print ("my goal is to become a successful developer and Chad xd")
print ("besides GOA, I love listening to the music")
print ("i listen to it everywhere")
print ("i play guitar and do taekwondo too")
print ("i like living with a healthy lifestyle")
print (" i hope i'll make friends in GOA")
print ("so the learning process will be more fun")
print ("i only had one lesson yet")
print ("but i love GOA already")
print ("becouse it's the best programming academy ever.")



print (20 + 20)
print (40 - 30)
print (50 * 2)
print (100/10)
print (200//4)
print (50 + 17)
print (60 - 20)
print (20 * 23)
print (30//3)
print (40/3)


print ("finished my homework")